name: dask-xgboost-nyctaxi
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Cut down version of coiled/benchmarks
  # https://github.com/coiled/benchmarks/blob/main/ci/environment.yml
  - coiled >=0.2.54
  - numpy ==1.24.4
  - pandas ==2.1.1
  - dask ==2023.9.2
  - distributed ==2023.9.2
  - dask-labextension ==7.0.0
  - dask-ml ==2023.3.24
  - fsspec ==2023.9.1
  - s3fs ==2023.9.1
  - gcsfs ==2023.9.1
  - pyarrow ==13.0.0
  - jupyterlab ==4.0.6
  - lz4 ==4.3.2
  - ipywidgets ==8.0.4  # FIXME https://github.com/dask/distributed/issues/7688
  - scikit-learn ==1.3.1
  - click ==8.1.7
  - cftime ==1.6.2
  - msgpack-python ==1.0.6
  - cloudpickle ==2.2.1
  - tornado ==6.3.3
  - toolz ==0.12.0
  - zict ==3.0.0
  - xgboost ==1.7.6
  - optuna ==3.3.0
  - scipy ==1.11.2
  - sqlalchemy ==2.0.21
  - bokeh ==3.2.2
  - gilknocker ==0.4.1
  - openssl >1.1.0g
  # These are specific to this project
  - matplotlib=3.8.0
  - seaborn=0.12.2
