name: dask-xgboost-nyctaxi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10

  - coiled-runtime=0.2.1
  # These will be in coiled-runtime=0.2.2
  - optuna=3.1.0
  - scipy=1.10.0
  - sqlalchemy=1.4.46

  - matplotlib=3.6.3
  - seaborn=0.12.2
